/// Flutter icons IconsInstagram
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsInstagram
///      fonts:
///       - asset: fonts/IconsInstagram.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IconsInstagram {
  IconsInstagram._();

  static const _kFontFam = 'IconsInstagram';
  static const String? _kFontPkg = null;

  static const IconData paperAirplaneFlying =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ovalBlackSpeechBubble =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagramlogo =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
